CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_LOG=y

# Networking
CONFIG_NETWORKING=y
CONFIG_NET_L2_ETHERNET=y
CONFIG_NET_OFFLOAD=y
CONFIG_WIFI=y
CONFIG_NET_IPV4=y
CONFIG_NET_UDP=y
CONFIG_NET_SOCKETS=y

# Random Number Generator (Required for Networking)
CONFIG_TEST_RANDOM_GENERATOR=y
CONFIG_ENTROPY_DEVICE_RANDOM_GENERATOR=y

# Optimization
CONFIG_SPEED_OPTIMIZATIONS=y
CONFIG_ISR_STACK_SIZE=2048
CONFIG_MAIN_STACK_SIZE=4096

# Memory
CONFIG_HEAP_MEM_POOL_SIZE=4096

# LED Strip
CONFIG_LED_STRIP=y
CONFIG_WS2812_STRIP_RPI_PICO_PIO=y
